export const ATTENDANCE_CONSTANTS = {
  // Schema Versions
  SCHEMA_VERSION_STAFF: 1,
  SCHEMA_VERSION_BARCODE: 1,
  SCHEMA_VERSION_ATTENDANCE: 1,
  SCHEMA_VERSION_ATTENDANCE_LOG: 1,

  // Business Rules
  DUPLICATE_SCAN_TIMEOUT_MS: 5 * 60 * 1000, // 5 minutes
  MAX_BARCODE_REGENERATION_ATTEMPTS: 5,
  MAX_ACTIVE_BARCODES_PER_STAFF: 1,

  // Formatting
  DATE_FORMAT: 'YYYY-MM-DD',
  TIME_FORMAT: 'HH:mm:ss',

  // Naming & Prefixes
  BARCODE_PREFIX: 'BC',
  STAFF_PREFIX: 'STF',
};
